name: pltviz-dev
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - black>=19.10b0
  - matplotlib>=3.3.2
  - numpy>=1.19.2
  - packaging>=20.9
  - pandas>=1.2.1
  - pytest>=6.2.2
  - pytest-cov>=2.11.1
  - scipy>=1.6.0
  - seaborn>=0.11.1
  - pip:
      - colormath>=3.0.0
      - poli-sci-kit>=0.1.2.7
